### PR TITLE
Updated to support auto-wiring (Symfony 3.4+)

### PR DESCRIPTION
**Pull request by angelsk**
Symfony 3.4+ makes all services private by default in preparation for Symfony 4.

This PR auto-wires the Rollout services, which fixes the issue of not being able to add users to a feature flag in Symfony 3.4.

Also updates the controller to use auto-wired services and the built in Symfony controller methods - this removes all deprecated warnings from the Profiler log.

Auto-wiring has been in Symfony since 2, so this maintains BC (plus added in the old alias to maintain config BC).

### CODE REVIEW

**Comment by angelsk** [comment]
@richardfullmer Sorry about the multiple commits - I hadn't noticed the Scrutinizer results before, so I wanted to tidy my code - and it sort of snowballed from there.

**Comment by angelsk** [comment]
@richardfullmer Any chance of a review on this please?

**Comment by richardfullmer** [comment]
It seems unlikely that I'll merge this as is without some BC in place.  This change completely breaks implementations that use Symfony2, and explicitly requires >=3.4.  In order to do that, we'd have to fork the code base into multiple maintained versions, per semver requirements.

Instead of doing that, I'd rather make these new implementations work _with_ symfony2 and symfony3.4 and 4.  If we do that, it won't require maintaining multiple branches within this repository for which version of symfony a user may be using.

**Comment by angelsk** [comment]
@richardfullmer Apologies, autowiring has been there since Symfony 2 so I've reverted the composer requirements back.

**Comment by angelsk** [comment]
@richardfullmer Ok, all done.  Removed anything PHP7 specific, reverted composer changes (but did add PHP 7.2 as a Travis platform for future compat).  As I said above auto-wiring has been in since Symfony 2, so should be all good for Symfony 2->4

**Pull request closed without merging**
